version: '3.8'

services:
   app:
      build:
         context: ./config/php
      container_name: php
      volumes:
         - .:/var/www/html
      networks:
         - app-network
      environment:
         - DB_HOST=db
         - DB_NAME=${DB_NAME}
         - DB_USER=${DB_USER}
         - DB_PASSWORD=${DB_PASSWORD}
         - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

   web:
      image: nginx:latest
      container_name: nginx
      volumes:
         - ./public/:/var/www/html/public
         - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
         - ./config/nginx/logs/:/var/log/nginx
      ports:
         - "80:80"
      depends_on:
         - app
      networks:
         - app-network

   db:
      image: mysql
      container_name: mysql
      environment:
         MYSQL_DATABASE: "${DB_NAME}"
         MYSQL_USER: "${DB_USER}"
         MYSQL_PASSWORD: "${DB_PASSWORD}"
         MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      volumes:
         - ./config/mysql/data:/var/lib/mysql
      ports:
         - "3306:3306"
      networks:
         - app-network

networks:
   app-network:
      driver: bridge

volumes:
   db_data: