version: '3.8'

services:
   app:
      build:
         context: ./.docker/php
      container_name: php
      volumes:
         - ./src:/var/www/html
      networks:
         - app-network

   web:
      image: nginx:latest
      container_name: nginx
      volumes:
         - ./src:/var/www/html
         - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
         - ./.docker/nginx/logs/:/var/log/nginx
      ports:
         - "8080:80"
      depends_on:
         - app
      networks:
         - app-network

   db:
      image: mysql
      container_name: mysql
      environment:
         MYSQL_ROOT_PASSWORD: rootpass
         MYSQL_DATABASE: mydb
         MYSQL_USER: user
         MYSQL_PASSWORD: userpass
      volumes:
         - ./.docker/mysql/data:/var/lib/mysql
      ports:
         - "3306:3306"
      networks:
         - app-network

networks:
   app-network:
      driver: bridge
